name: Auto Merge Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != 'github-actions[bot]' # 避免机器人自己的 PR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for mergeable state
        run: |
          for i in {1..10}; do
            MERGEABLE=$(gh pr view ${{ github.event.pull_request.number }} --json mergeable --jq .mergeable)
            if [ "$MERGEABLE" = "MERGEABLE" ]; then
              echo "PR is mergeable"
              echo "mergeable=true" >> $GITHUB_OUTPUT
              break
            elif [ "$MERGEABLE" = "CONFLICTING" ]; then
              echo "PR has conflicts"
              echo "mergeable=false" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "Mergeable state not ready, waiting..."
            sleep 5
          done
          if [ -z "$MERGEABLE" ]; then
            echo "Failed to determine mergeable state"
            echo "mergeable=false" >> $GITHUB_OUTPUT
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: check-merge

      - name: Auto-merge PR
        if: steps.check-merge.outputs.mergeable == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               -X PUT \
               -d '{"merge_method":"merge"}' \
               https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge
          if [ $? -eq 0 ]; then
            echo "PR merged successfully"
            # 可选：删除源分支
            gh api -X DELETE \
              -H "Accept: application/vnd.github+json" \
              /repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }}
          else
            echo "Failed to merge PR"
            exit 1
          fi