name: Auto Merge PRs with Label

# 使用 pull_request_target 以便 fork PR 可以访问 secrets
on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge PRs
        uses: pascalgn/automerge-action@v0.16.4
        env:
          # 必须在仓库 Secrets 中添加 PAT，名字为 PERSONAL_TOKEN
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          MERGE_METHOD: merge          # 合并方式，可改为 squash 或 rebase
          MERGE_LABELS: "automerge"    # 只自动合并带此标签的 PR
          MERGE_DELETE_BRANCH: true    # 自动删除 PR 来源分支（同仓库分支会被删除，fork 的不会被删除）
          MERGE_COMMIT_MESSAGE: body
          MERGE_COMMIT_TITLE: "[PR] {{title}}"
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 10000
