name: Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge PRs when all checks pass
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: merge
          MERGE_LABELS: ""       # 禁用标签要求
          MERGE_COMMIT_MESSAGE: title+body
          MERGE_DELETE_BRANCH: true
